-- Create employee table
CREATE TABLE IF NOT EXISTS employee (
  id INT AUTO_INCREMENT PRIMARY KEY,
  employee_id VARCHAR(255) NOT NULL,
  department VARCHAR(255) NOT NULL,
  designation VARCHAR(255) NOT NULL,
  qualification VARCHAR(255) NOT NULL,
  work_exp VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  surname VARCHAR(255) NOT NULL,
  father_name VARCHAR(255) NOT NULL,
  mother_name VARCHAR(255) NOT NULL,
  contact_no VARCHAR(255) NOT NULL,
  emeregency_contact_no VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE,
  dob DATE NOT NULL,
  marital_status VARCHAR(255) NOT NULL,
  date_of_joining DATE NOT NULL,
  date_of_leaving DATE DEFAULT NULL,
  local_address VARCHAR(255) NOT NULL,
  permanent_address VARCHAR(255) NOT NULL,
  note TEXT DEFAULT NULL,
  image VARCHAR(255) DEFAULT NULL,
  password VARCHAR(255) NOT NULL,
  gender VARCHAR(255) NOT NULL,
  acount_title VARCHAR(255) NOT NULL,
  bank_account_no VARCHAR(255) NOT NULL,
  bank_name VARCHAR(255) NOT NULL,
  ifsc_code VARCHAR(255) NOT NULL,
  bank_branch VARCHAR(255) NOT NULL,
  payscale VARCHAR(255) NOT NULL,
  basic_salary VARCHAR(255) NOT NULL,
  epf_no VARCHAR(255) NOT NULL,
  contract_type VARCHAR(255) NOT NULL,
  shift VARCHAR(255) NOT NULL,
  location VARCHAR(255) NOT NULL,
  resume VARCHAR(255) NOT NULL,
  joining_letter VARCHAR(255) NOT NULL,
  resignation_letter VARCHAR(255) NOT NULL,
  other_document_name VARCHAR(255) NOT NULL,
  other_document_file VARCHAR(255) NOT NULL,
  is_active TINYINT(1) DEFAULT 1,
  is_superadmin TINYINT(1) DEFAULT 0,
  verification_code VARCHAR(255) DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert default superadmin (password: superadmin - hashed with bcrypt)
INSERT INTO employee (
  employee_id, department, designation, qualification, work_exp,
  name, surname, father_name, mother_name, contact_no, emeregency_contact_no,
  email, dob, marital_status, date_of_joining, local_address, permanent_address,
  password, gender, acount_title, bank_account_no, bank_name, ifsc_code,
  bank_branch, payscale, basic_salary, epf_no, contract_type, shift, location,
  resume, joining_letter, resignation_letter, other_document_name, other_document_file,
  is_active, is_superadmin
) VALUES (
  'EMP001', 'Administration', 'Super Admin', 'Master', '5+',
  'Super', 'Admin', 'N/A', 'N/A', '0000000000', '0000000000',
  'superadmin@gmail.com', '1990-01-01', 'Single', CURDATE(), 'Admin Office', 'Admin Office',
  '$2b$10$gwMM9HxZf6d9YwlM7SEE8.6YJqIvNn23eBezDNMWyqsXDHzXmigHG', 'Male', 'N/A', '0000000000', 'N/A', 'N/A',
  'N/A', 'N/A', '0', 'N/A', 'Permanent', 'Day', 'Head Office',
  '', '', '', '', '',
  1, 1
) ON DUPLICATE KEY UPDATE email = email;
